# Generated by Django 4.2.6 on 2023-10-29 21:10

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_category_options_alter_contact_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("-dt",),
                "verbose_name": "заказ",
                "verbose_name_plural": "список заказов",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ("email",),
                "verbose_name": "пользователь",
                "verbose_name_plural": "список пользователей",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[("shop", "Магазин"), ("customer", "Покупатель")],
                default="customer",
                max_length=8,
                verbose_name="тип пользователя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={
                    "unique": "Пользователь с таким именем уже существует."
                },
                help_text="Необходимо не более 150 символов. Только буквы, цифры и знаки @/./+/-/_",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
